### ISSUE TITLE
ModuleNotFoundError: No module named 'numba'

### ISSUE THREAD

**Issue by bukosabino** [hudson-and-thames/mlfinlab#160]
**Describe the bug**
module `numba` is not correctly imported when installing `mlfinlab`. 

**To Reproduce**
1. install `mlfinlab` library

```sh
pip install mlfinlab
```

2. Import ewma

```python
from mlfinlab.util.fast_ewma import ewma
```

```sh
>>> from mlfinlab.util.fast_ewma import ewma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vant/env3.7/lib/python3.7/site-packages/mlfinlab/__init__.py", line 6, in <module>
    import mlfinlab.data_structures as data_structures
  File "/home/vant/env3.7/lib/python3.7/site-packages/mlfinlab/data_structures/__init__.py", line 16, in <module>
    from mlfinlab.data_structures.imbalance_data_structures import get_dollar_imbalance_bars, get_volume_imbalance_bars, \
  File "/home/vant/env3.7/lib/python3.7/site-packages/mlfinlab/data_structures/imbalance_data_structures.py", line 24, in <module>
    from mlfinlab.util.fast_ewma import ewma
  File "/home/vant/env3.7/lib/python3.7/site-packages/mlfinlab/util/__init__.py", line 5, in <module>
    from mlfinlab.util.fast_ewma import ewma
  File "/home/vant/env3.7/lib/python3.7/site-packages/mlfinlab/util/fast_ewma.py", line 9, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'
```

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1

**Comment by proskurin** [comment]
Hia, @bukosabino 
Do you have numba installed?

**Comment by proskurin** [comment]
We have a small problem with package dependencies, we will try to solve it next release

**Comment by bukosabino** [comment]
Hi @proskurin ,

Of course, I can work with `mlfinlab` installing `numba`. I only write this issue to let you know.

I can help you with the package dependencies if you want.

Fantastic work guys. I am in love with this library!

**Comment by aditya1702** [comment]
@bukosabino Thank you! Glad to know you like the work :)

**Comment by Jackal08** [comment]
Fixed in this PR: https://github.com/hudson-and-thames/mlfinlab/pull/187
