### ISSUE TITLE
cannot run HierarchicalRiskParity

### ISSUE THREAD

**Issue by rconnor0001** [hudson-and-thames/mlfinlab#446]
the code is from url: https://hudsonthames.org/portfolio-optimisation-with-mlfinlab-hierarchical-risk-parity/

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from mlfinlab.portfolio_optimization import HierarchicalRiskParity

prices = pd.read_csv(r'W:\user\stats\Machine Learning\ML Code tests\assetalloc1.csv', 
                         parse_dates=True, 
                         index_col='Dates')

price = prices.sort_values(by='Dates')

# constructing HRP portfolio - Single Linkage

hrp = HierarchicalRiskParity()

hrp.allocate(asset_names=prices.columns,
             asset_prices=prices,
             linkage='single')
```

The received error is:

```
runcell(0, 'W:/User/stats/Machine Learning/ML Code tests/hudson and thames optimization model test.py')
Traceback (most recent call last):

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\array_ops.py", line 149, in na_arithmetic_op
    result = expressions.evaluate(op, str_rep, left, right)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\computation\expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\computation\expressions.py", line 121, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\computation\expressions.py", line 70, in _evaluate_standard
    return op(a, b)

TypeError: unsupported operand type(s) for /: 'str' and 'float'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "W:\User\stats\Machine Learning\ML Code tests\hudson and thames optimization model test.py", line 26, in <module>
    linkage='single')

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\mlfinlab\portfolio_optimization\hrp.py", line 72, in allocate
    asset_returns = self.returns_estimator.calculate_returns(asset_prices=asset_prices)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\mlfinlab\portfolio_optimization\returns_estimators.py", line 68, in calculate_returns
    asset_returns = asset_prices.pct_change()

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\generic.py", line 10086, in pct_change
    rs = data.div(data.shift(periods=periods, freq=freq, axis=axis, **kwargs)) - 1

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\__init__.py", line 767, in f
    new_data = left._combine_frame(right, pass_op, fill_value)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\frame.py", line 5300, in _combine_frame
    new_data = ops.dispatch_to_series(self, other, _arith_op)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\__init__.py", line 419, in dispatch_to_series
    new_data = expressions.evaluate(column_op, str_rep, left, right)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\computation\expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\computation\expressions.py", line 121, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\computation\expressions.py", line 70, in _evaluate_standard
    return op(a, b)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\__init__.py", line 388, in column_op
    return {i: func(a.iloc[:, i], b.iloc[:, i]) for i in range(len(a.columns))}

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\__init__.py", line 388, in <dictcomp>
    return {i: func(a.iloc[:, i], b.iloc[:, i]) for i in range(len(a.columns))}

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\common.py", line 64, in new_method
    return method(self, other)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\__init__.py", line 503, in wrapper
    result = arithmetic_op(lvalues, rvalues, op, str_rep)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\array_ops.py", line 197, in arithmetic_op
    res_values = na_arithmetic_op(lvalues, rvalues, op, str_rep)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\array_ops.py", line 151, in na_arithmetic_op
    result = masked_arith_op(left, right, op)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\array_ops.py", line 94, in masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])

TypeError: unsupported operand type(s) for /: 'str' and 'str'

```

This is odd because the code was running fine until Friday evening. 

Your tools are much appreciated... thanks in advance for any help!

**Comment by Jackal08** [comment]
Hi @rconnor0001, 

Please double check that it's not on your side. We haven't touched the codebase so everything is stable. If it worked on Friday then it's super likely to be on your side. 

Best regards
Jacques
