### ISSUE TITLE
Help: ou_model cannot find root out-of-sample

### ISSUE THREAD

**Issue by kingwongf** [hudson-and-thames/mlfinlab#470]
Hi @PanPip 
I tried to run this 
`fig = ou_model.plot_levels(mid_prices[['BTC-GBP','ETH-GBP']]['2020-11-13 08:05:02':], stop_loss=True)`

Got this error

```/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/mlfinlab/optimal_mean_reversion/ou_model.py:541: IntegrationWarning: Extremely bad integrand behavior occurs at some points of the
  integration interval.
  calculated_f = quad(f_func, 0, np.inf)[0]
/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/mlfinlab/optimal_mean_reversion/ou_model.py:541: IntegrationWarning: Extremely bad integrand behavior occurs at some points of the
  integration interval.
  calculated_f = quad(f_func, 0, np.inf)[0]
/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/mlfinlab/optimal_mean_reversion/ou_model.py:541: IntegrationWarning: Extremely bad integrand behavior occurs at some points of the
  integration interval.
  calculated_f = quad(f_func, 0, np.inf)[0]
/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/mlfinlab/optimal_mean_reversion/ou_model.py:541: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  calculated_f = quad(f_func, 0, np.inf)[0]
/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/mlfinlab/optimal_mean_reversion/ou_model.py:541: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  calculated_f = quad(f_func, 0, np.inf)[0]
/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/mlfinlab/optimal_mean_reversion/ou_model.py:541: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  calculated_f = quad(f_func, 0, np.inf)[0]
Traceback (most recent call last):
  File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-9f99eb8b8da9>", line 7, in <module>
    fig = ou_model.plot_levels(mid_prices[['BTC-GBP','ETH-GBP']]['2020-11-13 08:05:02':], stop_loss=True)
  File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/mlfinlab/optimal_mean_reversion/ou_model.py", line 488, in plot_levels
    graph[0].axhline(self.optimal_liquidation_level(), label="optimal liquidation level",
  File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/mlfinlab/optimal_mean_reversion/ou_model.py", line 650, in optimal_liquidation_level
    sol = root_scalar(equation, bracket=bracket)
  File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/scipy/optimize/_root_scalar.py", line 249, in root_scalar
    r, sol = methodc(f, a, b, args=args, **kwargs)
  File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/scipy/optimize/zeros.py", line 780, in brentq
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
ValueError: f(a) and f(b) must have different signs
```

`ou_model.description()` returns the same error. It seems there's a problem in integration and root finding. Does that mean the model cannot find an entry or exit point? 
Many thanks!

**Comment by vlrie** [comment]
Hello @kingwongf ! Thank you for reaching out!

It seems to me the problem lies in the optimal liquidation level calculation. It might be that there is no optimal liquidation level for the data and model parameters provided. Hence, while the description function tries to calculate optimal levels it gives the same feedback.

There are a few probable causes:
The provided data combined with model parameters like transaction cost and discount rate might not have an optimal level of entry/exit
The data that you are using might break the integral calculation for the function that is involved in the root-finding process

Can you please provide the dataset and the input parameters that you are using so I could reproduce the issue?

**Comment by kingwongf** [comment]
Thanks! @vlrie
Of course, please see attached.
The params as followed,

```
ou_model = OrnsteinUhlenbeck()
mean_revert_pair = ['BTC-GBP','ETH-GBP']

ou_model.fit(mid_prices[mean_revert_pair], data_frequency='D', discount_rate=0.0,
             transaction_cost=[0.000, 0.000], start='2020-11-12 16:05:02', end='2020-11-13 08:05:02', stop_loss=None)

print(ou_model.check_fit())

# fig = ou_model.plot_levels(mid_prices[['BTC-GBP','ETH-GBP']]['2020-11-13 08:05:02':], stop_loss=True)
fig = ou_model.plot_levels(mid_prices[mean_revert_pair]['2020-11-13 08:05:02':], stop_loss=True)
```
This reminds me currently the module does not support data_frequency='s' so I used 'D' as it's the closest available. But I don't see the param is being used anywhere. 

I have also tried transaction costs of [0.005, 0.005].

**Comment by vlrie** [comment]
Hello again! 
Thank you for providing the data! I managed to reproduce your results. 

There are a few things that can be done to improve your results: 
 

- Using daily data. 

This approach is more tailored for the strategies with a longer holding period - daily data works best.

- Using smaller training samples.

Samples that are too large cause the integrals necessary for the root-finding to diverge, since the number of observations is included in its' calculation.

Hope it helps to achieve better results!
