### ISSUE TITLE
Error when importing mlfinlab

### ISSUE THREAD

**Issue by GreatNewHope** [hudson-and-thames/mlfinlab#483]
**Describe the bug**
I am using WSL Ubuntu 20. I install mlfinlab with no errors and when importing it, I get errors

**To Reproduce**
conda create -n mlfinlab_env python=3.7
conda activate mlfinlab
pip install mlfinlab
python
import mlfinlab

**Traceback error**
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/mlfinlab/__init__.py", line 22, in <module>
    import mlfinlab.portfolio_optimization as portfolio_optimization
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/mlfinlab/portfolio_optimization/__init__.py", line 5, in <module>
    from mlfinlab.portfolio_optimization.modern_portfolio_theory import CriticalLineAlgorithm
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/mlfinlab/portfolio_optimization/modern_portfolio_theory/__init__.py", line 5, in <module>
    from mlfinlab.portfolio_optimization.modern_portfolio_theory.mean_variance import MeanVarianceOptimisation
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/mlfinlab/portfolio_optimization/modern_portfolio_theory/mean_variance.py", line 9, in <module>
    import cvxpy as cp
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/cvxpy/__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/cvxpy/atoms/geo_mean.py", line 20, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/cvxpy/utilities/power_tools.py", line 18, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/cvxpy/atoms/affine/reshape.py", line 18, in <module>
    from cvxpy.atoms.affine.hstack import hstack
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/cvxpy/atoms/affine/hstack.py", line 18, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/cvxpy/atoms/affine/affine_atom.py", line 22, in <module>
    from cvxpy.cvxcore.python import canonInterface
  File "/home/marcos/miniconda3/envs/mrh_trading/lib/python3.7/site-packages/cvxpy/cvxcore/python/__init__.py", line 3, in <module>
    import _cvxcore
ImportError: numpy.core.multiarray failed to import

**Desktop (please complete the following information):**
 - OS: Windows 10 WSL Ubuntu 20

**Comment by GreatNewHope** [comment]
No difference when `conda install -c conda-forge scs` and `conda install -c anaconda ecos`. Neither when uninstalling numpy and installing latest conda version 1.19.2

**Comment by GreatNewHope** [comment]
Solved by installing numpy version 1.20

**Comment by GreatNewHope** [comment]
This issue looks like it has been fixed in version 1.1.10 of cvxpy. To prevent this package from breaking mlfinlab's import, you could maybe try to move the requirement of cvxpy==1.1.1 to cvxpy==1.1.10

**Comment by Jackal08** [comment]
Hi @GreatNewHope, 

Thanks for this. We have updated all the libraries to work with the latest versions and the problem has been resolved. Will be moving this thread to #487.

Best regards
Jacques Joubert
