### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by ebweinstein** [hudson-and-thames/mlfinlab#545]
**Describe the bug**
Can't install on Mac.

I tried various python versions including 3.10 and 3.11 of mlfinlab on a fresh environment. Getting Process finished with exit code 137 (interrupted by signal 9:SIGKILL)

I tried docker too and getting this erro:

mlfinlab-1  | INFO:root:Fetching remote package with payload: {'api_key': 'clz...42c', 'python_version': '311', 'package': 'mlfinlab'}
mlfinlab-1  | Traceback (most recent call last):
mlfinlab-1  |   File "/download_and_install.py", line 40, in <module>
mlfinlab-1  |     response.raise_for_status()
mlfinlab-1  |   File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
mlfinlab-1  |     raise HTTPError(http_error_msg, response=self)
mlfinlab-1  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://package-server-392714.nw.r.appspot.com/installer?api_key=clz0k5yuj0001mf08wjnuj42c&python_version=311&package=mlfinlab

Guessing maybe your license server is down. 

Also your slack is not available.

I just purchased this and pretty disappointed.

**Comment by GrazMir** [comment]
Same here. Did yo have any success?
